wsgi/openshift/Administrador/urls.py
from django.conf.urls import patterns, url
from Administrador import views
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
	url(r'^perfil/$', login_required(views.perfil_admi), name='perfil_admi'),
	url(r'^inicio_sesion/$', views.inicio_sesi_admi, name='inicio_sesi_admi'),
	url(r'^cerrar_sesion/$', views.cerrar_sesion_admi, name='cerrar_sesion_admi'),
	url(r'^uploader/$', views.upload_handler, name='upload_handler'),
	
	# url(r'^probandoproyecto/$', views.probando, name='probando'),
	# url(r'^ingresar_producto/$', views.creando_user, name='ingresar_producto'),
	# url(r'^iniciarsesion/$',views.iniciar_sesion, name='iniciar_sesion'),
)

wsgi/openshift/Productos/urls.py
from django.conf.urls import patterns, url
from Productos import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	# url(r'^probandoproyecto/$', views.probando, name='probando'),
	url(r'^registrarse/$', views.creando_user, name='crear_user'),
	url(r'^iniciar_sesion/$',views.iniciar_sesion, name='iniciar_sesion'),
)

wsgi/openshift/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'openshift.views.home', name='home'),
    # url(r'^openshift/', include('openshift.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('Productos.urls', namespace="Productos")), #here go /Productos beside r'^'
    url(r'^administrador/', include('Administrador.urls', namespace="Administrador")), #here go /Productos beside r'^'
    url(r'^compras/', include('Compras.urls', namespace="Compras")),
    # url(r'^', include('Nucleo.urls', namespace="Nucleo")), #here go /Productos beside r'^'
)

wsgi/openshift/templates/mediaStore/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		{% block titulo %} {% endblock %}     
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta name="description" content="" />
		<meta name="author" content="" />

		<!-- Le styles -->
		<link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet" />
		<link href="{{ STATIC_URL }}css/style.css" rel="stylesheet" />
		<link href="{{ STATIC_URL }}css/icon-style.css" rel="stylesheet" />
		<link href="{{ STATIC_URL }}css/bootstrap-responsive.css" rel="stylesheet" />
		<link href="{{ STATIC_URL }}source/jquery.fancybox.css" rel="stylesheet" />
		<link href="{{ STATIC_URL }}css/datepicker.css" rel="stylesheet" />
		

		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

		<!-- Le fav and touch icons -->
		<link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.ico" type="image/x-icon" />
		<link rel="icon" href="{{ STATIC_URL }}img/favicon.ico" type="image/x-icon" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>

	<body>

		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container-fluid">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
					<a class="brand" href="{% url 'Productos:index' %}">
						<img width="150px" height="50px" src="{{ STATIC_URL }}img/logoTiendaVirtual.png" />
					</a>
					<div class="nav-collapse">
						<ul class="nav">
				<li class="divider-vertical"></li>
							<li><a href="about.html">About</a></li>
				<li class="divider-vertical"></li>
							<form class="navbar-search pull-left" action="" />
								<input type="text" class="search-query span2" placeholder="Search" required="" />
							</form>
				<li class="divider-vertical"></li>
						</ul>
						<ul class="nav pull-right">
						<li class="divider-vertical"></li>

						{% if user.is_authenticated %}
							{% if user.is_superuser %}
						<li class="gravatar"><a href="profile.html"></a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Administrador {{ user.username }} <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'Administrador:perfil_admi' %}"><i class="icon-user"></i>  Configuraciones de Cuenta</a></li>
								<li class="divider"></li>
								<li><a href="{% url 'Administrador:cerrar_sesion_admi' %}"><i class="icon-off"></i> Salir</a></li>
							</ul>
						</li>
							{% else %}
						<li class="gravatar"><a href="profile.html"></a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }} <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="account_setting.html"><i class="icon-user"></i> Configuraciones de Cuenta</a></li>
								<li class="divider"></li>
								<li><a href="{% url 'Administrador:cerrar_sesion_admi' %}"><i class="icon-off"></i> Salir</a></li>
							</ul>
						</li>  
							{% endif %}
						{% else %}
						<li><a href="{% url 'Administrador:inicio_sesi_admi' %}"><i class="icon-lock"></i> Inicia Sesion</a></li>
						<li class="divider-vertical"></li>
						<li><a href="{% url 'Productos:crear_user' %}"><i class="icon-edit"></i> Registrate</a></li>
						<li class="divider-vertical"></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</li>
						{% endif %}

						<li class="divider-vertical"></li>
					</ul>
					</div><!--/.nav-collapse -->
				</div>
			</div>
		</div>
		<!-- Le javascript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="{{ STATIC_URL }}js/jquery-1.10.2.min.js"></script>
		<script src="{{ STATIC_URL }}js/bootstrap.js"></script>
		<script src="{{ STATIC_URL }}js/datepicker.js"></script>
		<!-- <script src="{{ STATIC_URL }}js/image-gallery.js"></script> -->
		<script src="{{ STATIC_URL }}js/jquery.mousewheel-3.0.6.pack.js"></script>
		<script src="{{ STATIC_URL }}source/jquery.fancybox.js"></script>
		
		{% block contenido %} {% endblock %}  

		{% block numsPaginacion %} {% endblock %}      
		
		<div class="container footer">
				<hr class="alt" />
				<div class="row">
						<div class="span6">&copy; 2013 tiendaVirtual. Todos los derechos reservados.</div>
						<div class="span6">
								<ul>
										<li><a href="#">Terms Of Service</a></li>
										<li><a href="#">Privacy</a></li>
								</ul>
						</div>
				</div>
		</div>

		
		
	</body>
</html>

wsgi/openshift/templates/mediaStore/inicio_sesi_admi.html
{% extends "base.html" %}  
{% block titulo %}<title>Iniciar Sesión Admi</title> {% endblock %}     

{% block contenido %}  
<div class="account-container btm10">

	<div class="form-content clearfix">
    
		<form method="post" />{% csrf_token %}

			<h1><i class="iconbig-lock"></i> Inicio Sesión Admin</h1>	
            
			<div class="login-fields">
            
				<p>Inicia Sesión con tu cuenta Admin:</p>

				{% if formIniSesiAdmi.non_field_errors %}
				<div class="field">
						<div class="alert alert-danger">
							{{ formIniSesiAdmi.non_field_errors }}
						</div>
						<br>
				</div>		
				{% endif %}
                
				<div class="field">
					<label for="username">Username:</label>
					<!-- <input type="text" id="username" name="username" value="" placeholder="Username" class="login username-field" required="" /> -->		
					{{ formIniSesiAdmi.usuario }}
				</div> <!-- /field -->

				<div class="field">
					<label for="password">Password:</label>
					<!-- <input type="password" id="password" name="password" value="" placeholder="Password" class="login password-field" required="" /> -->
					{{ formIniSesiAdmi.clave }}
				</div> <!-- /password -->

			</div> <!-- /login-fields -->			

			<div class="login-actions">

				<span class="login-checkbox">

					<input id="Field" name="Field" type="checkbox" class="field login-checkbox" value="First Choice" tabindex="4" />

					<label class="choice" for="Field">Mantenerme Logueado</label>

				</span>

				<input type="submit" name="submit" value="Iniciar" class="btn-signin btn btn-primary" />
                <a href="#" class="btn-signin btn">Cancelar</a>
                

			</div> <!-- .actions -->


			<!-- <div class="login-social marg10-btm">

				<p>Sign in using social network:</p>

					<a href="#" class="btn"><img src="img/twitter-18.png" /> Signin with twitter</a>

					<a href="#" class="btn"><img src="img/facebook-18.png" /> Signin with facebook</a>			

			</div> -->
            
            <p><a href="#">¿ Olvidaste tu Contraseña ?</a></p>

		</form>

	</div> <!-- /form-content -->

</div> <!-- /account-container -->
{% endblock %}

wsgi/openshift/templates/mediaStore/inicio_sesion.html
{% extends "base.html" %}  
{% block titulo %}<title>Iniciar Sesión</title> {% endblock %}     

{% block contenido %}  
<div class="account-container btm10">

	<div class="form-content clearfix">
    
		<form action="./" method="post" />{% csrf_token %}

			<h1><i class="iconbig-lock"></i> Inicia Sesión</h1>	
            
			<div class="login-fields">
            
				<p>Inicia Sesión con tu cuenta Registrada:</p>
                
				<div class="field">

					<label for="username">Usuario:</label>

					<input type="text" id="username" name="username" value="" placeholder="Usuario" class="login username-field" required="" />

				</div> <!-- /field -->

				<div class="field">

					<label for="password">Password:</label>

					<input type="password" id="password" name="password" value="" placeholder="Contraseña" class="login password-field" required="" />

				</div> <!-- /password -->

			</div> <!-- /login-fields -->			

			<div class="login-actions">

				<span class="login-checkbox">

					<input id="Field" name="Field" type="checkbox" class="field login-checkbox" value="First Choice" tabindex="4" />

					<label class="choice" for="Field">Keep me signed in</label>

				</span>

				<input type="submit" name="submit" value="Sign in" class="btn-signin btn btn-primary" />
                <a href="#" class="btn-signin btn">Cancel</a>
                

			</div> <!-- .actions -->


			<div class="login-social marg10-btm">

				<p>Sign in using social network:</p>

					<a href="#" class="btn"><img src="img/twitter-18.png" /> Signin with twitter</a>

					<a href="#" class="btn"><img src="img/facebook-18.png" /> Signin with facebook</a>			

			</div>
            
            <p><a href="#">Forgot your password ?</a></p>

		</form>

	</div> <!-- /form-content -->

</div> <!-- /account-container -->
{% endblock %}

wsgi/openshift/templates/mediaStore/paginacion.html
{% extends "base.html" %}  

{% block paginacion %} 
<div class="container">
        <div class="pagination">
        <ul>
          <li class="disabled"><a href="#" title="Go to the first page">&laquo; First</a></li>
          <li><a href="#" title="Go to the previous page">&larr;</a></li>
          <li class="active"><a href="#">1</a></li>
          <li><a href="#">2</a></li>
          <li><a href="#">..</a></li>
          <li><a href="#">8</a></li>
          <li><a href="#">9</a></li>
          <li><a href="#" title="Go to the next page">&rarr;</a></li>
          <li><a href="#" title="Go to the last page">Last &raquo;</a></li>
        </ul>
      </div>
</div>
{% endblock %}

wsgi/openshift/templates/mediaStore/registrarse.html
{% extends "base.html" %}  
{% block titulo %}<title>Registrarse</title> {% endblock %}     

{% block contenido %}  
<div class="account-container">

	<div class="form-content clearfix">
    
		<form method="post" />{% csrf_token %}

			<h1><i class="iconbig-note-write"></i> Registrarse</h1>	
            
			<div class="login-fields">
            
				<p>Ingresa tus datos:</p>

				{% if formRegister.non_field_errors %}
				<div class="field">
						<div class="alert alert-danger">
							{{ formRegister.non_field_errors }}
						</div>
						<br>
				</div>		
				{% endif %}
                
				<div class="field">

					<label for="username">Username:</label>

					<!-- <input type="text" id="username" name="username" value="" placeholder="Username" class="login username-field" required="" /> -->
					{{ formRegister.usuario }}
				</div> <!-- /field -->

				<div class="field">
					<label for="username">Nombre:</label>					
					{{ formRegister.nombre }}
				</div>

				<div class="field">
					<label for="username">Apellidos:</label>					
					{{ formRegister.apellidos }}
				</div>
                
        		<div class="field">

					<label for="email">Email:</label>

					<!-- <input type="email" id="email" name="email" value="" placeholder="Email" class="login email-field" required="" /> -->
					{{ formRegister.correo }}

				</div> <!-- /field -->


				<div class="field">

					<label for="password">Password:</label>

					<!-- <input type="password" id="password" name="password" value="" placeholder="Password" class="login password-field" required="" /> -->
					{{ formRegister.clave }}
					
					{% if  formRegister.clave.errors %}
					<div class="alert alert-danger">{{ formRegister.clave.errors }}</div>
					{% endif %}

				</div> <!-- /password -->

				<div class="field">

					<label for="password">Password:</label>

					<!-- <input type="password" id="password" name="password" value="" placeholder="Password" class="login password-field" required="" /> -->
					{{ formRegister.clave_confirmar }}

					{% if  formRegister.clave_confirmar.errors %}
					<div class="alert alert-danger">{{ formRegister.clave_confirmar.errors }}</div>
					{% endif %}

				</div> <!-- /password -->

			</div> <!-- /login-fields -->			

			<div class="login-actions">

				<input type="submit" name="submit" value="Registrate" class="btn-signin btn btn-primary" />
                
                <a href="#" class="btn-signin btn">Cancelar</a>

			</div> <!-- .actions -->


			<!-- <div class="login-social marg10-btm">

				<p>Sign up using social network:</p>

					<a href="#" class="btn"><img src="img/twitter-18.png" /> Signup with twitter</a>

					<a href="#" class="btn"><img src="img/facebook-18.png" /> Signup with facebook</a>			

			</div> -->

		</form>

   </div> <!-- /form-content -->

</div> <!-- /account-container -->
{% endblock %}
     
<!-- {% block paginacion %}  {% endblock %}     -->

wsgi/openshift/templates/mediaStore/registrarseCompras.html
{% extends "base.html" %}  
{% block titulo %}<title>Registrarse</title> {% endblock %}     

{% block contenido %}  
<div class="account-container">

	<div class="form-content clearfix">
    
		<form method="post" />{% csrf_token %}

			<h1><i class="iconbig-note-write"></i> Registrarse</h1>	
            
			<div class="login-fields">
            
				<p>Ingresa tus datos:</p>

				{% if formRegister.non_field_errors %}
				<div class="field">
						<div class="alert alert-danger">
							{{ formRegister.non_field_errors }}
						</div>
						<br>
				</div>		
				{% endif %}
                
				<div class="field">

					<label for="username">Username:</label>

					<!-- <input type="text" id="username" name="username" value="" placeholder="Username" class="login username-field" required="" /> -->
					{{ formRegister.usuario }}
				</div> <!-- /field -->

				<div class="field">
					<label for="username">Nombre:</label>					
					{{ formRegister.nombre }}
				</div>

				<div class="field">
					<label for="username">Apellidos:</label>					
					{{ formRegister.apellidos }}
				</div>
                
        		<div class="field">

					<label for="email">Email:</label>

					<!-- <input type="email" id="email" name="email" value="" placeholder="Email" class="login email-field" required="" /> -->
					{{ formRegister.correo }}

				</div> <!-- /field -->


				<div class="field">

					<label for="password">Password:</label>

					<!-- <input type="password" id="password" name="password" value="" placeholder="Password" class="login password-field" required="" /> -->
					{{ formRegister.clave }}
					
					{% if  formRegister.clave.errors %}
					<div class="alert alert-danger">{{ formRegister.clave.errors }}</div>
					{% endif %}

				</div> <!-- /password -->

				<div class="field">

					<label for="password">Password:</label>

					<!-- <input type="password" id="password" name="password" value="" placeholder="Password" class="login password-field" required="" /> -->
					{{ formRegister.clave_confirmar }}

					{% if  formRegister.clave_confirmar.errors %}
					<div class="alert alert-danger">{{ formRegister.clave_confirmar.errors }}</div>
					{% endif %}

				</div> <!-- /password -->

			</div> <!-- /login-fields -->			

			<div class="login-actions">

				<input type="submit" name="submit" value="Registrate" class="btn-signin btn btn-primary" />
                
                <a href="#" class="btn-signin btn">Cancelar</a>

			</div> <!-- .actions -->


			<!-- <div class="login-social marg10-btm">

				<p>Sign up using social network:</p>

					<a href="#" class="btn"><img src="img/twitter-18.png" /> Signup with twitter</a>

					<a href="#" class="btn"><img src="img/facebook-18.png" /> Signup with facebook</a>			

			</div> -->

		</form>

   </div> <!-- /form-content -->

</div> <!-- /account-container -->
{% endblock %}
     
<!-- {% block paginacion %}  {% endblock %}     -->

wsgi/openshift/templates/mediaStore/test.html
{% extends "base.html" %}  
{% block titulo %}<title>Perfil</title> {% endblock %}     

{% block contenido %} 
	<script type="text/javascript">
	$(function(){		
		$('.datepicker').datepicker({
			format: 'mm-dd-yyyy'
		});
	});
	</script>
	<form method="post"> {% csrf_token %}
		{{form_adherir_promocion.as_p}}
	</form>	
</body>
</html>
{% endblock %}

wsgi/openshift/templates/mediaStore/upload.html
{% extends 'base.html' %}
<!-- {% load filetransfers %} -->
<!-- {% block title %}Upload file to Blobstore{% endblock %} -->

{% block contenido %}

<h1>Upload</h1>
{% load filetransfers %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% render_upload_data upload_data %}
  <table>{{ form }}</table>
  <input type="submit" value="Upload" />
</form>


{% endblock %}